// **********************************************************************
// Parsed By TarsParser(2.4.5), Generated By tars2node(20200707)
// TarsParser Maintained By <TARS> and tars2node Maintained By <superzheng>
// Generated from "Verify.tars" by Client Mode
// **********************************************************************

/* eslint-disable */

"use strict";

var assert    = require("assert");
var TarsStream = require("@tars/stream");
var TarsError  = require("@tars/rpc").error;

var _hasOwnProperty = Object.prototype.hasOwnProperty;
var _makeError = function (data, message, type) {
    var error = new Error(message || "");
    error.request = data.request;
    error.response = {
        "costtime" : data.request.costtime
    };
    if (type === TarsError.CLIENT.DECODE_ERROR) {
        error.name = "DECODE_ERROR";
        error.response.error = {
            "code" : type,
            "message" : message
        };
    } else {
        error.name = "RPC_ERROR";
        error.response.error = data.error;
    }
    return error;
};

var civetAdminCenter = civetAdminCenter || {};
module.exports.civetAdminCenter = civetAdminCenter;

civetAdminCenter.VerifyProxy = function () {
    this._name    = undefined;
    this._worker  = undefined;
};

civetAdminCenter.VerifyProxy.prototype.setTimeout = function (iTimeout) {
    this._worker.timeout = iTimeout;
};

civetAdminCenter.VerifyProxy.prototype.getTimeout = function () {
    return this._worker.timeout;
};

civetAdminCenter.VerifyProxy.prototype.setVersion = function (iVersion) {
    this._worker.version = iVersion;
};

civetAdminCenter.VerifyProxy.prototype.getVersion = function () {
    return this._worker.version;
};

civetAdminCenter.E_VERIFY_CODE = {
    "EVC_TOKEN_EXPIRE" : -3,
    "EVC_ERR_TOKEN" : -2,
    "EVC_SYS_ERR" : -1,
    "EVC_SUCC" : 0
};
civetAdminCenter.E_VERIFY_CODE._classname = "civetAdminCenter.E_VERIFY_CODE";
civetAdminCenter.E_VERIFY_CODE._write = function(os, tag, val) { return os.writeInt32(tag, val); };
civetAdminCenter.E_VERIFY_CODE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); };

civetAdminCenter.VeifyReq = function() {
    this.token = "";
    this.verifyHeaders = new TarsStream.Map(TarsStream.String, TarsStream.String);
    this.body = new TarsStream.BinBuffer;
    this._classname = "civetAdminCenter.VeifyReq";
};
civetAdminCenter.VeifyReq._classname = "civetAdminCenter.VeifyReq";
civetAdminCenter.VeifyReq._write = function (os, tag, value) { os.writeStruct(tag, value); };
civetAdminCenter.VeifyReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
civetAdminCenter.VeifyReq._readFrom = function (is) {
    var tmp = new civetAdminCenter.VeifyReq;
    tmp.token = is.readString(0, true, "");
    tmp.verifyHeaders = is.readMap(1, false, TarsStream.Map(TarsStream.String, TarsStream.String));
    tmp.body = is.readBytes(2, false, TarsStream.BinBuffer);
    return tmp;
};
civetAdminCenter.VeifyReq.prototype._writeTo = function (os) {
    os.writeString(0, this.token);
    os.writeMap(1, this.verifyHeaders);
    os.writeBytes(2, this.body);
};
civetAdminCenter.VeifyReq.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
civetAdminCenter.VeifyReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
civetAdminCenter.VeifyReq.prototype.toObject = function() { 
    return {
        "token" : this.token,
        "verifyHeaders" : this.verifyHeaders.toObject(),
        "body" : this.body.toObject()
    };
};
civetAdminCenter.VeifyReq.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "token") && (this.token = json.token);
    _hasOwnProperty.call(json, "verifyHeaders") && (this.verifyHeaders.readFromObject(json.verifyHeaders));
    _hasOwnProperty.call(json, "body") && (this.body.readFromObject(json.body));
    return this;
};
civetAdminCenter.VeifyReq.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
civetAdminCenter.VeifyReq.new = function () {
    return new civetAdminCenter.VeifyReq();
};
civetAdminCenter.VeifyReq.create = function (is) {
    return civetAdminCenter.VeifyReq._readFrom(is);
};

civetAdminCenter.VeifyRsp = function() {
    this.ret = 0;
    this.uid = "";
    this.context = "";
    this._classname = "civetAdminCenter.VeifyRsp";
};
civetAdminCenter.VeifyRsp._classname = "civetAdminCenter.VeifyRsp";
civetAdminCenter.VeifyRsp._write = function (os, tag, value) { os.writeStruct(tag, value); };
civetAdminCenter.VeifyRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
civetAdminCenter.VeifyRsp._readFrom = function (is) {
    var tmp = new civetAdminCenter.VeifyRsp;
    tmp.ret = is.readInt32(0, true, 0);
    tmp.uid = is.readString(1, false, "");
    tmp.context = is.readString(2, false, "");
    return tmp;
};
civetAdminCenter.VeifyRsp.prototype._writeTo = function (os) {
    os.writeInt32(0, this.ret);
    os.writeString(1, this.uid);
    os.writeString(2, this.context);
};
civetAdminCenter.VeifyRsp.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
civetAdminCenter.VeifyRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
civetAdminCenter.VeifyRsp.prototype.toObject = function() { 
    return {
        "ret" : this.ret,
        "uid" : this.uid,
        "context" : this.context
    };
};
civetAdminCenter.VeifyRsp.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "ret") && (this.ret = json.ret);
    _hasOwnProperty.call(json, "uid") && (this.uid = json.uid);
    _hasOwnProperty.call(json, "context") && (this.context = json.context);
    return this;
};
civetAdminCenter.VeifyRsp.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
civetAdminCenter.VeifyRsp.new = function () {
    return new civetAdminCenter.VeifyRsp();
};
civetAdminCenter.VeifyRsp.create = function (is) {
    return civetAdminCenter.VeifyRsp._readFrom(is);
};

var __civetAdminCenter_Verify$verify$IF = {
    "name" : "verify",
    "return" : "int32",
    "arguments" : [{
        "name" : "req",
        "class" : "civetAdminCenter.VeifyReq",
        "direction" : "in"
    }, {
        "name" : "rsp",
        "class" : "civetAdminCenter.VeifyRsp",
        "direction" : "out"
    }]
};

var __civetAdminCenter_Verify$verify$IE = function (req) {
    var os = new TarsStream.TarsOutputStream();
    os.writeStruct(1, req);
    return os.getBinBuffer();
};

var __civetAdminCenter_Verify$verify$ID = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0),
                "arguments" : {
                    "rsp" : is.readStruct(2, true, civetAdminCenter.VeifyRsp)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __civetAdminCenter_Verify$verify$PE = function (req, __$PROTOCOL$VERSION) {
    var tup = new TarsStream.UniAttribute();
    tup.tupVersion = __$PROTOCOL$VERSION;
    tup.writeStruct("req", req);
    return tup;
};

var __civetAdminCenter_Verify$verify$PD = function (data) {
    try {
        var tup = data.response.tup;
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : tup.readInt32("", 0),
                "arguments" : {
                    "rsp" : tup.readStruct("rsp", civetAdminCenter.VeifyRsp)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __civetAdminCenter_Verify$verify$ER = function (data) {
    throw _makeError(data, "Call Verify::verify failed");
};

civetAdminCenter.VerifyProxy.prototype.verify = function (req) {
    var version = this._worker.version;
    if (version === TarsStream.Tup.TUP_SIMPLE || version === TarsStream.Tup.TUP_COMPLEX) {
        return this._worker.tup_invoke("verify", __civetAdminCenter_Verify$verify$PE(req, version), arguments[arguments.length - 1], __civetAdminCenter_Verify$verify$IF).then(__civetAdminCenter_Verify$verify$PD, __civetAdminCenter_Verify$verify$ER);
    } else {
        return this._worker.tars_invoke("verify", __civetAdminCenter_Verify$verify$IE(req), arguments[arguments.length - 1], __civetAdminCenter_Verify$verify$IF).then(__civetAdminCenter_Verify$verify$ID, __civetAdminCenter_Verify$verify$ER);
    }
};
civetAdminCenter.VerifyProxy.verify = __civetAdminCenter_Verify$verify$IF;



